git:
    submodules: false

language: php
php:
    - 7.1

install:

before_script:
    - travis_retry composer install --no-interaction --prefer-dist

script:
    - vendor/bin/tester tests
    - vendor/bin/phpcs src/ --standard=vendor/pd/coding-standard/src/PeckaCodingStandard/ruleset.xml
    - vendor/bin/phpcs src/ --standard=vendor/pd/coding-standard/src/PeckaCodingStandardStrict/ruleset.xml
    - vendor/bin/phpstan.phar analyse -l 1 src

cache:
    directories:
        - $HOME/.composer/cache
